# Site settings
title: "武汉抵抗军"
description: "Resistance Wuhan Official Website"
baseurl: "/zh" # the subpath of your site
url: "http://resistance-wh.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rogue
